site_name: P4wnP1 Official Wiki
repo_url: https://github.com/mame82/P4wnP1
edit_uri: edit/master
theme: readthedocs

pages:
- Home: 'README.md'
- FAQ: 'FAQ.md'
- Getting Started:
  - Installation: 'Getting-Started-Subfolder/Installation.md'
  - 'Getting Started': 'Getting-Started-Subfolder/Getting-Started.md'
  - Setup.cfg: 'Getting-Started-Subfolder/Setup.cfg.md'
- Payloads:
  - Overview: 'Payload-Subfolder/Payload-Home.md'
  - Backdoor:
    - Payload: 'Payload-Subfolder/Backdoor-Payload.md'
    - 'Commandline Interface': 'Payload-Subfolder/Backdoor-Commands.md'
  - Frontdoor: 'Payload-Subfolder/Frontdoor-Payload.md'
  - 'Windows 10 Lockpicker': 'Payload-Subfolder/Windows-10-Lockpicker.md'
  - 'Stealing Browser Credentials': 'Payload-Subfolder/Stealing-Browser-Credentials.md'
- 'OS Independent features': 'OS-Independent-features-Subfolder/OS-independent-features-Home.md'
- 'P4wnP1 W exclusive features':
  - Overview: 'P4wnP1-W/RasPi0-W-Home.md'
  - 'Wifi Hotspot': 'P4wnP1-W/ifi-Hotspot.md'
  - 'Wifi Client': 'P4wnP1-W/Wifi-Client.md'
  - 'Bluetooth': 'P4wnP1-W/Bluetooth-Connectivity.md'
  - 'Reverse SSH tunnel': 'P4wnP1-W/AutoSSH.md'
- Troubleshooting: 'Troubleshooting.md'
- Contributing:
    - Contributing: 'Contributing-Subfolder/Contributing-Home.md'
    - 'Payload Development': 'Contributing-Subfolder/Module-development.md'
    - 'Other ways to Contribute': 'Contributing-Subfolder/Other-Ways-to-Contribute.md'
- 'Wiki TODO list': 'ToDo.md'


mkdocs.yml
docs/
  README.md
  FAQ.md
  Troubleshooting.md
  Advanced-Features.md
  Getting-Started-Subfolder/Installation.md
  Getting-Started-Subfolder/Getting-Started.md
  Getting-Started-Subfolder/Setup.cfg.md
  Payload-Subfolder/Payload-Home.md
  Payload-Subfolder/Windows-10-Lockpicker.md
  Payload-Subfolder/Stealing-Browser-Credentials.md
  Payload-Subfolder/Frontdoor-Payload.md
  Payload-Subfolder/Backdoor-Subfolder/Backdoor-Payload.md
  Payload-Subfolder/Backdoor-Subfolder/Backdoor-Commands.md
  OS-Independent-features-Subfolder/OS-independent-features-Home.md
  P4wnP1-W/RasPi0-W-Home.md
  P4wnP1-W/Wifi-Hotspot.md
  P4wnP1-W/Wifi-Client.md
  P4wnP1-W/Bluetooth-Connectivity.md
  P4wnP1-W/AutoSSH.md
  Contributing-Subfolder/Contributing-Home.md
  Contributing-Subfolder/Module-development.md
  Contributing-Subfolder/Other-Ways-to-Contribute.md
  ToDo.md
