site_name: P4wnP1 Official Wiki
repo_url: https://github.com/mame82/P4wnP1/
edit_uri: '../P4wnP1-Wiki/edit/master/docs/'
theme_dir: 'mkdocs-material/material'
site_favicon: 'img/p4wnp1-logo.png'
google_analytics: ['UA-71330457-1', 'p4wnp1.readthedocs.io']

markdown_extensions:
  - admonition
  - toc(permalink=true)
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.keys

extra:
  font:
    code: 'monospace'

pages:
- Home: 'index.md'
- FAQ: 'FAQ.md'
- Getting Started:
  - Installation: 'Getting-Started-Subfolder/Installation.md'
  - 'Getting Started': 'Getting-Started-Subfolder/Getting-Started.md'
  - Setup.cfg: 'Getting-Started-Subfolder/Setup.cfg.md'
- Payloads:
  - Overview: 'Payload-Subfolder/Payload-Home.md'
  - Backdoor:
    - Payload: 'Payload-Subfolder/Backdoor-Subfolder/Backdoor-Payload.md'
    - 'Commandline Interface': 'Payload-Subfolder/Backdoor-Subfolder/Backdoor-Commands.md'
  - Frontdoor: 'Payload-Subfolder/Frontdoor-Payload.md'
  - 'Windows 10 Lockpicker': 'Payload-Subfolder/Windows-10-Lockpicker.md'
  - 'Stealing Browser Credentials': 'Payload-Subfolder/Stealing-Browser-Credentials.md'
- 'OS Independent features': 'OS-independent-features-Subfolder/OS-independent-features-Home.md'
- 'P4wnP1 W exclusive features':
  - Overview: 'P4wnP1-W/RasPi0-W-Home.md'
  - 'Wifi Hotspot': 'P4wnP1-W/Wifi-Hotspot.md'
  - 'Wifi Client': 'P4wnP1-W/Wifi-Client.md'
  - 'Bluetooth': 'P4wnP1-W/Bluetooth-Connectivity.md'
  - 'Reverse SSH tunnel': 'P4wnP1-W/AutoSSH.md'
- Troubleshooting: 'Troubleshooting.md'
- 'Advanced Features': 'Advanced-Features.md'
- Contributing:
    - Contributing: 'Contributing-Subfolder/Contributing-Home.md'
    - 'Payload Development': 'Contributing-Subfolder/Module-development.md'
    - 'Other ways to Contribute': 'Contributing-Subfolder/Other-Ways-to-Contribute.md'
- 'Wiki TODO list': 'ToDo.md'
